DROP TABLE IF EXISTS DeviceCheckIn;
DROP TABLE IF EXISTS Device;

CREATE OR REPLACE TABLE Device
(
	id          BIGINT      NOT NULL DEFAULT UUID_SHORT(),
	timeCreated DATETIME    NOT NULL,
	timeZone    VARCHAR(30) NOT NULL,
	secretKey   VARCHAR(50) NOT NULL,

	PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE DeviceCheckIn
(
	id      BIGINT   NOT NULL AUTO_INCREMENT,
	kDevice BIGINT   NOT NULL,
	time    DATETIME NOT NULL,
	battery INT      NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (kDevice) REFERENCES Device (id)
);
