DROP TABLE IF EXISTS DeviceUpdate;
DROP TABLE IF EXISTS Device;

CREATE OR REPLACE TABLE Device
(
	id          BIGINT NOT NULL DEFAULT UUID_SHORT(),
	timeCreated DATETIME        DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE DeviceUpdate
(
	id      BIGINT   NOT NULL AUTO_INCREMENT,
	kDevice BIGINT   NOT NULL,
	time    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	battery INT      NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (kDevice) REFERENCES Device (id)
);
