DROP TABLE IF EXISTS Alarm;
DROP TABLE IF EXISTS DeviceCheckIn;
DROP TABLE IF EXISTS Device;

CREATE OR REPLACE TABLE User
(
	id    BIGINT       NOT NULL DEFAULT UUID_SHORT(),
	email VARCHAR(200) NOT NULL,
	hash  VARCHAR(130) NOT NULL,
	salt  VARCHAR(130) NOT NULL,

	PRIMARY KEY (id),
	UNIQUE KEY (email)
);


CREATE OR REPLACE TABLE Device
(
	id          BIGINT      NOT NULL DEFAULT UUID_SHORT(),
	timeCreated DATETIME    NOT NULL,
	timeZone    VARCHAR(30) NOT NULL,
	secretKey   VARCHAR(50) NOT NULL,
	kOwner      BIGINT,

	PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE DeviceCheckIn
(
	id      BIGINT   NOT NULL AUTO_INCREMENT,
	kDevice BIGINT   NOT NULL,
	time    DATETIME NOT NULL,
	battery INT      NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (kDevice) REFERENCES Device (id)
);

CREATE OR REPLACE TABLE Alarm
(
	kDevice     BIGINT NOT NULL,
	isActive    BOOL   NOT NULL,
	time        TIME   NOT NULL,
	oneTimeDate DATE   NULL,

	PRIMARY KEY (kDevice),
	FOREIGN KEY (kDevice) REFERENCES Device (id)
);
